export const IPC_CHANNELS = {
  paletteOpen: 'palette.open',
  paletteClose: 'palette.close',
  commandParse: 'command.parse',
  searchResolve: 'search.resolve',
  actionExecute: 'action.execute',
  itemGet: 'item.get',
  itemCreate: 'item.create',
  itemUpdate: 'item.update',
  itemDelete: 'item.delete',
  vaultUnlock: 'vault.unlock',
  settingsGet: 'settings.get',
  settingsSet: 'settings.set',
  passkeySupport: 'passkey.support',
  passkeyList: 'passkey.list',
  passkeyCreate: 'passkey.create',
  passkeyAuthenticate: 'passkey.authenticate',
  passkeyDelete: 'passkey.delete',
  paletteTargetGet: 'palette.target.get',
  palettePrepare: 'palette.prepare',
  paletteFocus: 'palette.focus',
  paletteTargetChanged: 'palette.target.changed',
} as const
